services:
  client:
    build: ./client
    ports:
      - 8080:8080
    volumes:
      - ./client:/data
      - ./models:/models
    environment:
      - VUE_APP_API=rest
    networks:
      - proxy_net

  server:
    build:
      context: ./server
      target: build
    ports:
      - 3000
      - 9229:9229
    volumes:
      - ./server:/app
      - /app/node_modules
      - ./models:/models
    depends_on: 
      - server-database
    environment:
      MYSQL_HOST: 'server-database'
      MYSQL_DATABASE: 'ebdb'
      MYSQL_PORT: '3306'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ENV: 'STG'
      MYSQL_HOST_STG: 'junction.proxy.rlwy.net'
      MYSQL_PORT_STG: '22646'
      MYSQL_DATABASE_STG: 'railway'
      MYSQL_USER_STG: 'root'
      MYSQL_PASSWORD_STG: 'qGGubxnjCXABVmTGXzhgYYOQGDMFxyUy'
      SECRET: 'pippopluto'
      PORT: 3000
    networks:
      - proxy_net
    command: npm run dev
    
  server-database:
    image: mysql
    ports:
      - 3306:3306
    volumes:
      - ./db:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      MYSQL_DATABASE: 'ebdb'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    networks:
      - proxy_net
      
  proxy: 
    image: nginx 
    volumes: # mount custom config at runtime 
      - ./nginx.conf:/etc/nginx/conf.d/default.conf 
    links:
    - client:client # "app" is the hostname used in proxy_pass directive
    - server:server # "app" is the hostname used in proxy_pass directive
    ports: 
      - 80:80 
    networks:
      - proxy_net
networks:
  proxy_net:
    driver: bridge

    